services:
  appium:
    image: appium/appium:latest
    container_name: appium-android
    ports:
      - "4723:4723"
      - "8090:8090"
    environment:
      REMOTE_ADB: true
      ANDROID_DEVICES: $ANDROID_DEVICES
      REMOTE_ADB_POLLING_SEC: 10
      APPIUM_ADDITIONAL_PARAMS: --relaxed-security --allow-insecure chromedriver_autodownload --allow-insecure adb_shell
    volumes:
      - ${PWD}/build:/${PWD}/build
      # ADB context from host
      - ~/.android:/root/.android
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    cpus: 1
    mem_limit: 2048m
